"""Generate bounded authoring/growth/evolution probes. Run from the repository root.

This is a research expander, not supported gameplay content syntax. Controlled producers
stand in for missing extraction/imports. Generated TOML is loaded by the real Formats loader.
"""
from pathlib import Path
import copy
import json
import re
import tomllib

root = Path(__file__).parent
out = root / 'study-generated'
out.mkdir(exist_ok=True)
source = (root / 'connected.toml').read_text()
blocks = [b for b in re.split(r'(?=^\[)', source, flags=re.M) if b.startswith('[')]
def table(b):
    return b.splitlines()[0].strip('[]')
def named(b):
    m = re.search(r'^name\s*=\s*"([^"]+)"', b, re.M)
    return m.group(1) if m else ''
def document(bs):
    return '# Generated by content-study.py; controlled research content.\n' + '\n'.join(bs)
def emit(name, text):
    (out / (name + '.toml')).write_text(text)

# Omission probes distinguish loader dependencies from the function deliberately removed.
manifest = []
for key in ['layers', 'roads', 'lots', 'capacity', 'parking', 'trips', 'placement', 'jobs',
            'households', 'lattice', 'districts', 'hinterland', 'market', 'needs', 'shopping',
            'income_tax', 'treasury', 'life_stage']:
    name = 'omit-' + key
    emit(name, document([b for b in blocks if table(b) != key]))
    manifest.append({'name':name, 'group':'omission'})

# Start from the same connected circuit; remove unrelated repairs/geometry layers and
# retain its explicit layout, funding, demographics and purchase/pay settings.
lean = []
for b in blocks:
    if table(b) in ['layers','parking','market'] or named(b) in ['repairs','upkeep']:
        continue
    b = '\n'.join(l for l in b.splitlines() if 'resource = "repairs"' not in l) + '\n'
    lean.append(b)
emit('lean', document(lean))
manifest.append({'name':'lean', 'group':'bootstrap'})

# Reusable intent model: one basket, consumer names, and two prototype producers.
model = json.loads((root / 'content-model.json').read_text())
shared = document([b for b in blocks if not b.startswith('[[')
                   and table(b) not in ['shopping','income_tax']])

shared = '\n'.join(line for line in shared.splitlines() if not line.startswith(('education_', 'floor_tiles_per_place'))) + '\n'

def expand(m):
    gs=m['goods']; lines=[shared]
    lines += ['[[resource]]\nname = "money"\nfamily = "money"\n']
    for g in gs:
        lines += [f'[[resource]]\nname = "{g["name"]}"\nfamily = "good"\n']
    for g in gs:
        name=g['name']; trade='makes_'+name; kind='producer_'+name
        lines += [f'''[[business]]
name = "{trade}"
wage_per_day = 2048
pay_period_days = 7
shift_start_earliest_hour = 8
shift_start_latest_hour = 8
[[building]]
name = "{kind}"
premises = true
business = "{trade}"
bins = [ {{resource="{name}", owner="business", capacity={g['producer_capacity']}}}, {{resource="money", owner="business"}} ]
''']
        inputs = '[]' if 'input' not in g else '[ {scope="pool", resource="'+g['input']+'", amount=4} ]'
        lines += [f'''[[rule]]
name = "{kind}.produce"
kind = "{kind}"
rate = {m['source_every_ticks']}
apply = {{min=1, max=4}}
inputs = {inputs}
outputs = [ {{scope="local", resource="{name}", amount={g['output_per_firing']}}} ]
''']
    for consumer in m['consumers']:
        for v in range(m['variants']):
            kind=f'{consumer}_v{v}'
            bins=[]; rules=[]
            for g in gs:
                n=g['name']; numerator=g['daily_use']*m['consume_every_ticks']
                if numerator % 2048: raise ValueError('daily use is not exactly representable at this cadence')
                amount=numerator//2048
                # Each economic variant intentionally changes only storage cover.
                bins.append(f'{{resource="{n}", owner="occupant", capacity={g["daily_use"]*(g["home_days"]+v)}}}')
                rules += [f'''[[rule]]
name = "{kind}.buy.{n}"
kind = "{kind}"
rate = 8
apply = {{min=1, max=4}}
inputs = [ {{scope="pool", resource="{n}", amount={amount}}} ]
outputs = [ {{scope="local", resource="{n}", amount={amount}}} ]
[[rule]]
name = "{kind}.consume.{n}"
kind = "{kind}"
rate = {m['consume_every_ticks']}
apply = {{min=1, max=1}}
inputs = [ {{scope="local", resource="{n}", amount={amount}}} ]
outputs = []
''']
            lines += [f'[[building]]\nname="{kind}"\nhouses=true\nbins=[ '+', '.join(bins)+' ]\n'] + rules
    for i in range(m['life_stages']):
        lines += [f'[[life_stage]]\nname="stage_{i}"\nduration_days=64\nspread_days=0\n']
    prices=', '.join('{resource="'+g['name']+'", price=100}' for g in gs)
    lines += ['[[lattice]]\norigin_east_tiles=0\norigin_north_tiles=0\n',
              '[[hinterland]]\nedge="north"\nemigrant_balance_min=0\nemigrant_balance_max=0\nprices=[ '+prices+' ]\n']
    return '\n'.join(lines)

for c,g,v,stages in [(1,1,1,1),(2,1,1,1),(4,1,1,1),(4,2,1,1),(4,4,1,1),
                     (4,2,2,1),(4,2,4,1),(4,2,1,4),(4,2,1,8)]:
    m=copy.deepcopy(model)
    m['consumers']=[f'home_{i}' for i in range(c)]
    m['goods']=[dict(model['goods'][0],name=f'good_{i}') for i in range(g)]
    m['variants']=v; m['life_stages']=stages
    name=f'growth-c{c}-g{g}-v{v}-s{stages}'
    emit(name,expand(m)); manifest.append({'name':name,'group':'growth','consumers':c,'goods':g,'variants':v,'stages':stages})
emit('prototype',expand(model)); manifest.append({'name':'prototype','group':'prototype'})
tuned=copy.deepcopy(model); tuned['goods'][1]['daily_use']=48
emit('prototype-tuned',expand(tuned)); manifest.append({'name':'prototype-tuned','group':'prototype'})

# Evolution cases all branch from the same saved, inhabited connected city.
evolution={
 'comment':source+'\n# A presentation-only change.\n',
 'wage':source.replace('name = "teaching"\nwage_per_day    = 4096','name = "teaching"\nwage_per_day    = 8192'),
 'shared-consumption':source.replace('rate    = 256\napply   = { min = 1, max = 1 }\ninputs  = [ { scope = "local", resource = "sundries", amount = 4 } ]',
                                    'rate    = 256\napply   = { min = 1, max = 1 }\ninputs  = [ { scope = "local", resource = "sundries", amount = 6 } ]'),
 'rename-kind':source.replace('"school"','"academy"'),
 'rename-good':source.replace('"sundries"','"food"'),
 'remove-kind':document([b for b in blocks if not(table(b)=='building' and named(b)=='school')]),
 'opening-balance':source.replace('opening_balance = 4194304','opening_balance = 4194305'),
 'add-kind':source+'\n[[building]]\nname="new_home"\nhouses=true\nbins=[{resource="sundries", owner="occupant", capacity=128}]\n',
 'add-policy':source+'\n[[policy]]\nname="new_levy"\nsweeps="household"\ninterval=2048\napply={min=1,max=1}\ntransfer={from="local",to="global",resource="money",amount=1}\n',
}
newbs=[]
for b in blocks:
    if table(b)=='building' and named(b)=='shopfront':
        b=b.replace('bins = [','bins = [\n    {resource="food", owner="business", capacity=128},',1)
    if table(b)=='hinterland': b=b.replace('prices = [','prices = [\n    {resource="food", price=100},',1)
    newbs.append(b)
evolution['add-good-recipe']=document(newbs)+'''\n[[resource]]
name="food"
family="good"
[[rule]]
name="process_food"
kind="shopfront"
rate=8
apply={min=1,max=1}
inputs=[{scope="local",resource="sundries",amount=8}]
outputs=[{scope="local",resource="food",amount=4}]
'''
evolution['remove-kind'] = '\n'.join(line for line in evolution['remove-kind'].splitlines() if not line.startswith(('education_', 'floor_tiles_per_place'))) + '\n'
for name,text in evolution.items():
    assert text != source, name
    emit('evolve-'+name,text)
(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
# Current corpus counts are per file, not a fictitious combined base-game Ruleset.
corpus=[]
for p in sorted(Path('rulesets').glob('*.toml')):
    d=tomllib.loads(p.read_text())
    corpus.append({'file':p.name,'rules':len(d.get('rule',[])), 'kinds':len(d.get('building',[])),
                   'resources':len(d.get('resource',[])), 'policies':len(d.get('policy',[]))})
(root/'results/content-census.json').write_text(json.dumps(corpus,indent=2)+'\n')
print(f'Wrote {len(manifest)} scope/growth inputs and {len(evolution)} evolution cases to {out}')

def leaves(value, path=''):
    if isinstance(value,dict):
        return {k:v for key,item in value.items() for k,v in leaves(item,path+'/'+str(key)).items()}
    if isinstance(value,list):
        return {k:v for key,item in enumerate(value) for k,v in leaves(item,path+'/'+str(key)).items()}
    return {path:value}

measurements=[]
for entry in manifest:
    if entry['group']=='omission': continue
    d=tomllib.loads((out/(entry['name']+'.toml')).read_text())
    refs=sum(1 for p in leaves(d) if p.endswith(('/resource','/kind','/business')))
    measurements.append(dict(entry, rules=len(d.get('rule',[])), kinds=len(d.get('building',[])),
                             references=refs, scalar_fields=len(leaves(d))))
a=leaves(tomllib.loads((out/'prototype.toml').read_text()))
b=leaves(tomllib.loads((out/'prototype-tuned.toml').read_text()))
diff=[{'path':p,'before':a.get(p),'after':b.get(p)} for p in sorted(a.keys()|b.keys()) if a.get(p)!=b.get(p)]
assert len(diff)==8, diff
(root/'results/content-growth.json').write_text(json.dumps({'measurements':measurements,'one_intent_edit_expansion':diff},indent=2)+'\n')
