<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../src/Borough.Godot/CitySave.cs" Link="CitySave.cs" />
    <ProjectReference Include="../../../src/Borough.Core/Borough.Core.csproj" />
    <ProjectReference Include="../../../src/Borough.Formats/Borough.Formats.csproj" />
  </ItemGroup>
</Project>
